### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by pochih** [LeonCrashCode/AttentionTargetSentiment#6]
Hello, I've read your paper, it's really good and readable.
I am curious about some issues.

Q1: How do you tokenize/clean your dataset?
For example, in T-dataset, "it's" is written as "it ` s".
If split with space, it will be three words "it" & "`" & "s".
I think this is not good for LSTM to learn.
How do you deal with these cases?

Q2: You store the data with raw format and low format, what does it means?

Q3: I read your code, and find you change some words to UNK.
Here is my understand. You count the word, and change some singletons into UNK with probability 0.1, am I right?
What is the meaning of this step, why you choose prob 0.1 but not change all singletons into UNK ?

Q4: In impl/attention.cc line 483, you introduce lexicon score, but doesn't mention it in the paper.
What role does lexicon score plays?

Q5: You use GloVe word embedding, but there will exist some words not in GloVe. How do you initial the word embedding of these words?

Thanks for your reading!

**Comment by LeonCrashCode** [comment]
Thanks for your questions,

Q1: Yes you are right. but we did not deal with these cases. I suggest you use the Z-dataset for this task, because it has train/dev/test split
Q2: raw format is the original format of the sentence, low format changes all word into lowercase.
Q3: Yes, you are right. Here we try to add noise to training data with UNK, which ensure the UNK could be trained. prob 0.1 is empirical setting following related work.
Q4: the lexicon score is imported but not used. Sorry, I will clean the unused parts of codes later.
Q5: The UNK embeddings are the average embeddings of all the word embeddingds in Glove.

**Comment by pochih** [comment]
Thanks for your quick reply!
Help me a lot.
